Decoding the result of `urlread`
`urlread` has a parameter decode whose default value is set to True. As such, there is no need to call decode on the result of urlread.
The current version returns the following error: AttributeError: 'str' object has no attribute 'decode'